### ISSUE TITLE
Flasgger doesnt support basic auth

### ISSUE THREAD

**Issue by Anshul21** [flasgger/flasgger#103]
Following is my spec

```
"""
    This is the  user status API
    Call this api passing a linkedin user email and get back their status
    ---
    swagger: "2.0"
    tags:
      - User Status API
    securityDefinitions:
      basicAuth:
        type: basic
    parameters:
      - name: user_email
        in: path
        type: string
        required: true
        description: The user's email
    security:
      - basicAuth: []
    responses:
      500:
        description: Exception occurred during processing request
      400:
        description: No status found for user
      200:
        description: User's status
        schema:
          id: user_email
          properties:
            user:
              type: string
              description: The User's email
              default: xxxx@abc.com
            user_status:
              type: string
              description: The user'status
              default: completed

    """



```
Everything works fine except the basic auth
![screen shot 2017-05-18 at 9 27 16 am](https://cloud.githubusercontent.com/assets/7298709/26213025/5145d784-3bac-11e7-99a4-49280677fa53.png)

**Comment by rochacbruno** [comment]
I need help to resolve this

**Comment by frizner** [comment]
I've resolved the issue of authentication using the next code:
`swagger_template = {
        ...,
        'securityDefinitions': {
            'basicAuth': {
                'type': 'basic'
            }
        },
        ...
    }
Swagger(app, config=config[config_name].swagger_config, template=swagger_template)`

![image](https://user-images.githubusercontent.com/3438966/29333683-b612d394-81d2-11e7-97c9-a430dcbd0630.png)

**Comment by rochacbruno** [comment]
@frizner it would be nice to add it as an example and also include the image and code snippet in README.md
