### ISSUE TITLE
Exporting swagger spec JSON file programmatically

### ISSUE THREAD

**Issue by dmwesterhoff** [flasgger/flasgger#216]
Is there currently any way, without running the devel server to export the JSON file programmatically? We would like to decouple the documentation from the source, while still using the docstring style inline spec to actually generate the swagger docs. Any help here would be very much appreciated, not sure if this is possible/supported.

**Comment by rochacbruno** [comment]
It would be an interesting feature to add.

For now you can use the flask test client to make a call to /spec.json and get a JSON with the results.

**Comment by javabrett** [comment]
#222 allows the YAML to be detached into a `doc_dir`.

**Comment by rochacbruno** [comment]
I am reponing this, we solved one part which is decoupling the yaml files, but now we need something to staticaly generate the specs. Something like.

```bash
flask generate-swagger-specs --options /tmp/specs.json
generating the specs in /tmp/specs.json ...
```

We cna easily attach new commands to `flask.cli` on 1.1+ example: https://github.com/rochacbruno/talkshow/blob/master/talkshow/ext/cli.py

**Comment by xalien10** [comment]
Is it possible to export auto generated json specs file ?

**Comment by xalien10** [comment]
Isn't the flask api spec generation published yet? @arthurio

**Comment by arthurio** [comment]
@xalien10 The PR has been merged but it doesn't seem like there has been a release yet... @billyrrr when do you plan on making new releases?
