### ISSUE TITLE
uiversion 3 with blank url after initializing default data

### ISSUE THREAD

**Issue by huanghe314** [flasgger/flasgger#266]
I overwrite the default data with following code:  
```
# config.py
template = {
  "swagger": "2.0",
  "info": {
    "title": "KG Service API & Algorithm API",
    "description": "API for Knowledge Hub & Algorithm Hub",
    "contact": {
      "responsibleOrganization": "ME",
      "responsibleDeveloper": "Me",
      "email": "me@me.com",
      "url": "www.privacy.com",
    },
    "termsOfService": "",
    "version": "0.0.1"
  },
  "host": "mysite.com",  # overrides localhost:500
  "basePath": "/",  # base bash for blueprint registration
  "schemes": [
    "http"
  ],
  "operationId": "gskg_service_api"
}

# __init__.py
from flasgger import Flasgger
flask_swagger = Flasgger()
flask_swagger.init_app(app)
app.swag.template = template
```
Because I use factory pattern, I set the template with `app.swag.template` after looking up the source code.
The appearance on uiversion 3 looks strange just like screenshot below. 
The problem is that `the developer - Website` link to blank not the `www.privacy.com`
<img width="623" alt="screen shot 2018-11-21 at 11 29 45 pm" src="https://user-images.githubusercontent.com/12616602/48851292-9d784a00-ede5-11e8-88f2-65fc585ecaad.png">
On version 2, it looks good
<img width="618" alt="screen shot 2018-11-21 at 11 40 27 pm" src="https://user-images.githubusercontent.com/12616602/48851798-dfee5680-ede6-11e8-981e-2e7c95847175.png">
I suppose this is the problem in frontend, please help, I like the more modern uiversion 3 style

**Comment by pahrohfit** [comment]
You need to load your endpoints *first*, then the API:

```
def create_app(...):
    ...
    register_resources(app)  # load all of your endpoints here
    register_extensions(app) # `api.init_app(app)` happens here
    register_swagger(app) # `swag = Swagger(app)` happens here
    return app
```
