### ISSUE TITLE
Custom validation Error handling does not work when configuring validation via SwaggerView

### ISSUE THREAD

**Issue by BaturinM** [flasgger/flasgger#297]
When I configure Swagger instance with my own custom error handler:
`swagger = Swagger(app, config=config.SWAGGER_CONFIG, template=config.SWAGGER_TEMPLATE, validation_error_handler=my_own_handler)`
I still get the default handler.
It seems that the reason is:
https://github.com/rochacbruno/flasgger/blob/fef154f61d7afca548067be0c758c3dd71cc4c97/flasgger/marshmallow_apispec.py#L80
There must be validation_error_handler parameter passed to `flasgger.utils.validate`

**Comment by allrod5** [comment]
Hi @BaturinM, sorry for the long delay.

Can you provide an example test code to reproduce this bug?

**Comment by chaitan94** [comment]
Is this fix going to merged into the master branch anytime soon? I don't see any reason why it isn't merged yet.
