### ISSUE TITLE
This project is looking for new mantainers

### ISSUE THREAD

**Issue by rochacbruno** [flasgger/flasgger#300]
Hi,

I don't have enough time to dedicate to this project, also I am now working focused on Quality Engineering and test automation, web dev and API development with Flask is no more part of my daily work.

There are many people/companies relying on this project to serve API and I don't want to disappoint them.

## We need new maintainers

We need 2 more people to be included as maintainers of this project, currently it is only me and @javabrett but we are not able to handle all the work needed to do here.

**I'll still be here as maintainer, to ensure I can help with important decisions and setups and that the project is going on the right direction.**

### What we need?

- Move this project to an organization?
- Work to have proper dicummentation in place
- Review Pull Requests and Issues (there is a lot of issues in need of triage, labeling, answer)
- Keep an eye open for OPenApi Spec updates
- Keep eye open for Swagger UI updates

### Who can be a maintainer?

The preference is for people that is already on this list, (but if you want to be a maintainer and are not on that list you can comment here anyway, we will see) 
https://github.com/rochacbruno/flasgger/graphs/contributors

If you are on that list and wants to be added as a maintainer (rights on this repo and pypi for releases) please comment on this thread.

### What is your benefits of being a maintainer

- You are going to be features in https://github.com/rochacbruno/flasgger#top-contributors
- You will be added on the new file/section MAINTAINERS.md
- You will help open-source
- You will be praised as one of the people that will not let this project die
- You will have the satisfaction of having this project (which I assume you use) in a good shape!

## What next?

1. I am waiting for comments on this thread from people that wants to become a maintainer
2. I'll add people to the team and we will try to put this project in a good shape (updates, docs and issues resolved) 
3. If I can't find new maintainers in 3 months from now (Aug, 4, 2019), then, I'll try to move this project to an organization like https://github.com/jazzband
4. If I am not able to find new maintainers neither accepted on Jazzband or similar project in 4 months from now (Sept, 2019 )then, I'll archive this project (make it read-only), include a note on github and pypi, a deprecation warning on installation and let it available for fork only, I dont wanna do that!

Thanks! I hope we can continue this project together!

:+1:

**Comment by samizdis** [comment]
I'm happy to help with the Issues triage, reviewing PRs and getting the build passing the CI. Not too fussed about diving into the docs though.

**Comment by vitodsk** [comment]
I'd also like help as I can, in my understanding OAS 3 is not fully supported, and would like to start  improving that part.

**Comment by rochacbruno** [comment]
@samizdis @vitodsk please send a PR resolving at least one important issue and I'll add you as maintainer.

**Comment by belkka** [comment]
[Is it enough?](https://github.com/rochacbruno/flasgger/pull/310). Can I be a maintainer?

**Comment by samizdis** [comment]
:D @belkka you beat me to it :p

**Comment by jaitaiwan** [comment]
Hey Folks, we've reached the August 4th deadline, is this going to be kept here or put elsewhere? I have limited time but I'm able to help review pull requests

**Comment by rochacbruno** [comment]
@billyrrr are you able to take ownership and continue this project and also coordinate the contributors

**Comment by billyrrr** [comment]
Thank you for this wonderful opportunity, @rochacbruno . I will be glad to take over this project!

**Comment by jaitaiwan** [comment]
Bravo @billyrrr!  Thanks for taking the mantle
