### ISSUE TITLE
flasgger tried to find index.html in the wrong directory

### ISSUE THREAD

**Issue by chshpra** [flasgger/flasgger#344]
Hi everyone, this weird thing happened to me today. When I installed my pacakge (which imports and uses flasgger) to a Linux server and called the /apidocs/index.html, flasgger tried to find index.html in my package's directory (as you could see in the screenshot) instead of the flasgger's package directory. This didn't happen when I was testing on my MacBook.

Don't know if this is a bug or something I misconfigured. And no related content was found on google. Could someone give me some hints? Thanks!

![4001571996716_ pic_hd](https://user-images.githubusercontent.com/12208242/67561839-26170d00-f750-11e9-9a33-fdcc45422503.jpg)

**Comment by billyrrr** [comment]
Which version of Flasgger is installed? You can find out by typing `pip list`.

**Comment by chshpra** [comment]
I'm using version 0.9.3.

btw, I was able to solve this by setting the flask template directory and static directory to the flasgger template directory.
