### ISSUE TITLE
Dynamically add/remove routes

### ISSUE THREAD

**Issue by mike0sv** [flasgger/flasgger#346]
In my flask app I want to change routes dynamically. I was able to implement this in flask, but when I visit /apidocs, it does not reload changes and shows only routes that were there when I started the app. Is there a way to do this with flasgger?

**Comment by billyrrr** [comment]
I see that your routes are changed shortly after your initial flask app is loaded, but such change is only one-time, and intends to have the same effect as declaring it statically with less code. 

Does it work to call ```Swagger(app)``` after all routes are added dynamically?

**Comment by mike0sv** [comment]
actually, in my case it was easier just to recreate flask app completely, because there is no need to stay up during routing changes
