### ISSUE TITLE
Return list as response

### ISSUE THREAD

**Issue by sschiessl-bcp** [flasgger/flasgger#347]
Hello everyone,

in the example of https://github.com/flasgger/flasgger/blob/master/README.md#using-marshmallow-schemas it shows how to use nested to define a list as response. It returns e.g.
```
{
   'cmyk': ['cian', 'magenta', 'yellow', 'black']
}
```

How can I modify it such that it returns directly a list? For the above example, the expected return value would be 
```
['cian', 'magenta', 'yellow', 'black']
```

Is that something that would be considered wrong from a design perspective?

I found a way to do it, but it breaks the apidocs overview. I want a view that returns a list of orders. Currently, this is what I did

```
class OrderSchema(Schema):
    id = fields.String(description="Identifier")

class OrdersView(SwaggerView):
    decorators = None
    tags = ["user"]
    summary = "List orders"
    description = "Returns a list of all orders"
    parameters = None
    responses = {
        200: {"description": "OK", "schema": OrderSchema}
    }
    validation = False

    def get(self):
        orders = Oders()
        result = OrderSchema().dump(orders, many=True)
        return jsonify(result)
```
It works, but in the apidocs, the response value is now not a list, but only one OrderSchema object.
I could introduce a OrderListSchema, that has a nested OrderSchema field, but then the return value would not be directly the list, but a dict with the list in the field's name.

**Comment by billyrrr** [comment]
Sorry, but the current code does not support this feature. I think it may be incorrect from a design perspective: assume that your response content type is “application/json” then ```['cian', 'magenta', 'yellow', 'black']``` is not a valid json. You would have to turn it into 
```
{
   'cmyk': ['cian', 'magenta', 'yellow', 'black']
}
```

If you intend your response content type as “text/plain”, ("['cian', 'magenta', 'yellow', 'black']" string as an example), then it should be okay. You can probably specify it without a Schema object and as a string.

**Comment by sschiessl-bcp** [comment]
Thank you for that. I think a list would be valid JSON still from a design choice a primitive as direct response is not recommended. I found this after reading your hint and found it helpful

https://stackoverflow.com/questions/19623339/is-a-list-array-valid-json
