### ISSUE TITLE
apispec_1.json 404 not found at development server

### ISSUE THREAD

**Issue by zooozoo** [flasgger/flasgger#351]
Hi~! 
I'm using flasgger 0.9.2
The problem is when I deploy source code to ec2, The `/apidocs` page working properly with IP address and port. 
But with domain name, `/apidocs` page cannot get apispec_1.json (404 not found response) that I can check at Chrome development mode Network tab. 
The weird thing is that I can check apispec_1.json content through Chrome browser with the URL that is failed at `/apidocs` page.

Could anyone get me a hint for this kind of situation plz...

**Comment by billyrrr** [comment]
If it's possible, could you post the public IP address to your EC2 instance and the domain name? 

My email address is billrao@me.com

If not, then let me know, and I'll figure something else out.

**Comment by zooozoo** [comment]
Sorry. This should be closed... 
I can not check this kind of situation again. And this might be related to internal network something for security...
Thank for comment!

**Comment by tamarmot** [comment]
I am having the same issue, what was the resolution?
