### ISSUE TITLE
Servers Section not working with openapi 3.*.* version

### ISSUE THREAD

**Issue by aleksvidak** [flasgger/flasgger#366]
When switching to OpenApi 3.0.2, it is not possible to use servers section inside specification. 
https://swagger.io/docs/specification/api-host-and-base-path/

> In OpenAPI 3.0, you use the servers array to specify one or more base URLs for your API. servers replaces the host, basePath and schemes keywords used in OpenAPI 2.0. Each server has an url and an optional Markdown-formatted description.

It would be nice if we can add this one (or any other OAS3 field) to swagger configuration.

Something like [https://github.com/flasgger/flasgger/issues/318](https://github.com/flasgger/flasgger/issues/318)  can be done or even better add OPTIONAL_OAS3_FIELDS similar to OPTIONAL_FIELDS in [https://github.com/flasgger/flasgger/blob/master/flasgger/constants.py](https://github.com/flasgger/flasgger/blob/master/flasgger/constants.py).

Something like this:
**in base.py:**
instead of:
```
# enable 'components' when openapi_version is 3.*.*
if is_openapi3() and self.config.get("components"):
    data["components"] = self.config.get(
        'components'
    )
```
->
```
# enable oas3 fields when openapi_version is 3.*.*
optional_oas3_fields = self.config.get('optional_oas3_fields') or \
    OPTIONAL_OAS3_FIELDS
for key in optional_oas3_fields:
    if is_openapi3() and self.config.get(key):
        data[key] = self.config.get(key)
```

**in constants.py:**
```
OPTIONAL_OAS3_FIELDS = [
    'components', 'servers'
]
```
Does anybody know how to bypass this issue until some change is introduced to the code base?

**Comment by billyrrr** [comment]
Hi, @aleksvidak . The solution you offered seems good to me! Would you like to submit a pull request for that? I'll definitely merge it.

**Comment by aleksvidak** [comment]
Sure, could you grant me rights to push to the repo?

**Comment by billyrrr** [comment]
I can definitely grant that if you want to continue to work on features related to OpenAPI 3. You can submit this pull request for now and then we can see where to go from there ☺️

**Comment by billyrrr** [comment]
Merged in https://github.com/flasgger/flasgger/commit/d630b77ea53b960b0a9119af9f242d93b6e94272

**Comment by davidwangdw** [comment]
hey @aleksvidak can you describe a bit how to use this? i know it's been a while, but my configuration isn't working. i'm using this: 

`    swagger_config = {
        "openapi": "3.0.2",
        "title": title,
        "description": "",
        "termsOfService": "",
        "version": "",
        "swagger_ui": True,
        "servers": [
            {
                "url": "https://api.example.com/v1",
                "description": "Production server (uses live data)"
            },
            {
                "url": "https://sandbox-api.example.com:8443/v1",
                "description": "Sandbox server (uses test data)"
            }
        ],
        "headers": [
            ('Access-Control-Allow-Origin', '*')
        ],
        # some UI configurations
        "footer_text": "",
        "hide_top_bar": True,
        "doc_expansion": "list",
        "components": {
            "securitySchemes": {
                "authorization": {
                    "type": "apiKey",
                    "in": "header",
                    "name": "Authorization"
                }
            }
        }
    }`

but the "servers" label doesn't show up in my apispec_1.json. when i change it to "host", it shows up (but that's swagger 2.0). curiously enough, "components" still shows up, so i'm wondering why servers doesn't.
