### ISSUE TITLE
not using mashmallow or apispec, but flasgger wants me to install them

### ISSUE THREAD

**Issue by mike0sv** [flasgger/flasgger#384]
After updating to 0.9.4 from 0.9.3 I am unable to get to /apidocs page, it shows me 500 error with message "RuntimeError: Please install marshmallow and apispec" (and I dont want to)
Here is an (almost) minimal example, run it and go to http://localhost:5000/apidocs

```import flask
from flasgger import Swagger, swag_from

app = flask.Flask(__name__)
Swagger(app)

spec = {'requestBody': {'content': {'application/json': {'schema': {'properties': {'a': {'type': 'integer'}},
                                                                    'type': 'object'}}},
                        'required': True},
        'responses': {'200': {'content': {'application/json': {'schema': {'properties': {'data': {'type': 'string'},
                                                                                         'ok': {'type': 'boolean'}},
                                                                          'type': 'object'}}},
                              'description': 'successful response'},
                      '400': {'content': {'application/json': {'schema': {'properties': {'error': {'type': 'string'},
                                                                                         'ok': {'type': 'boolean'}},
                                                                          'type': 'object'}}},
                              'description': 'incorrect request'}},
        'summary': "Calls 'kek' method on model"}
swag = swag_from(spec)


@app.route('/kek', methods=['POST'])
@swag
def kek():
    return 'ok'


if __name__ == '__main__':
    app.run()
```
works fine with 0.9.3
flask version is 1.1.2, I am on mac (but problem persists inside docker so probably that's not relevant)

**Comment by billyrrr** [comment]
Thanks for creating this issue. The problem was caused by the invocation of ```convert_schema``` on all view methods, even when they do not contain a Schema. I have delayed ```RuntimeError``` to when ```convert_schema``` actually encounters a Schema. This should prevent ```convert_schema``` from throwing an error when all it has to do is to pass through all non-schema classes. Please try to install the current master, and keep me posted! Thank you.

**Comment by mike0sv** [comment]
Problem solved, on current master, thanks! Any hopes for minor release with this fix soon?
