### ISSUE TITLE
open interface doc is loading...

### ISSUE THREAD

**Issue by huwentao1** [flasgger/flasgger#387]
this is my version
```
Flask==1.0.2
flasgger==0.9.3
```
when I add a new interface,  open the interface doc is loading(run in the local and the test env).
![image](https://user-images.githubusercontent.com/43719888/79409276-1924f900-7fd0-11ea-85e0-637a1d1d3c0e.png)
in my local, nothing error info.
in my test env, warning:
![image](https://user-images.githubusercontent.com/43719888/79409734-3b6b4680-7fd1-11ea-864d-9c5b0c32822f.png)

I want to know under what circumstances it will loading, because there is no error message in the local environment.

**Comment by huwentao1** [comment]
Sorry, the problem is that I wrote the format wrong.
wrong:
```
responses:
        200:
            examples:
                data: {1: 222}
        400:
            description: {1: xxxx}
```
correct
```
responses:
        200:
            examples:
                data: {1: 222}
        400:
            examples: 
                data: {1: 222}
```

Because there is no error message, I always thought it was not a format problem. sorry

**Comment by abearxiong** [comment]
你知道为什么examples数据不显示吗？

例
```
responses:
        200:
            examples:
                data: {1: 222}
        400:
            examples: 
                data: {1: 222}
```

但是我的页面中，举例数据不显示，不显示{data:{1:222}}这种例子对象

**Comment by huwentao1** [comment]
> 你知道为什么examples数据不显示吗？
> 
> 例
> 
> ```
> responses:
>         200:
>             examples:
>                 data: {1: 222}
>         400:
>             examples: 
>                 data: {1: 222}
> ```
> 
> 但是我的页面中，举例数据不显示，不显示{data:{1:222}}这种例子对象

目前你这种情况我还没有遇到过。我目前遇到的这些问题，大部分都是格式写的不对导致的，例如出现了中文字符，value的值不是一个对象等等。你可以拿一个标准的格式改，最好不要自己写，很容易写错。

**Comment by abearxiong** [comment]
#### 悲伤

单纯的复制例子粘贴，examples的内容也不显示，版本flassger:0.9.3和0.9.2都是

弄低了一个版本好0.8.3就可以得到了，但是整个UI页面都变了

##### 0.8.3 版本具有examples

![image](https://user-images.githubusercontent.com/23001129/80857207-e55dfa80-8c82-11ea-9365-d347ef35f691.png)

##### 0.9.3 没有

![image](https://user-images.githubusercontent.com/23001129/80857223-0fafb800-8c83-11ea-94db-c92274b92061.png)

我不知道你的数据是怎么有的。

但是我的代码就是copy过来跑的。

![image](https://user-images.githubusercontent.com/23001129/80857251-45ed3780-8c83-11ea-9d8f-868bd5c44120.png)

**Comment by huwentao1** [comment]
> #### 悲伤
> 单纯的复制例子粘贴，examples的内容也不显示，版本flassger:0.9.3和0.9.2都是
> 我不知道你的数据是怎么有的。
> 但是我的代码就是copy过来跑的。

![image](https://user-images.githubusercontent.com/43719888/81157608-b95fb380-8fb9-11ea-8fef-ee6c9e8687c4.png)
我不确定是不是这个问题，不过你可以点击一下红色的地方试一下，是不是你默认进去就是直接切换到Model了
