### ISSUE TITLE
Issue importing Flasgger in Flask via Pycharm

### ISSUE THREAD

**Issue by bhanuteja2001** [flasgger/flasgger#400]
![Screenshot (121)](https://user-images.githubusercontent.com/44323155/82142568-e8e4aa80-985a-11ea-98b5-ce080c114023.png)
![Screenshot (122)](https://user-images.githubusercontent.com/44323155/82142572-eaae6e00-985a-11ea-8023-b62c0b2d38ab.png)

**Comment by arendondiosa** [comment]
@bhanuteja2001 Using pycharm, the best way to install packages is using the Python interpreter.
In some cases the project is connected to a different virtual environment than expected

<img width="978" alt="Screen Shot 2020-05-17 at 8 24 39 AM" src="https://user-images.githubusercontent.com/14989202/82148211-85d22400-9818-11ea-84a0-a4749df37452.png">

**Comment by arendondiosa** [comment]
@bhanuteja2001 Using pycharm, the best way to install packages is using the Python interpreter.
In some cases the project is connected to a different virtual environment than expected

<img width="978" alt="Screen Shot 2020-05-17 at 8 24 39 AM" src="https://user-images.githubusercontent.com/14989202/82148256-c2058480-9818-11ea-9215-7e820360e3f3.png">

**Comment by bhanuteja2001** [comment]
@arendondiosa Thanks it works!!
