### ISSUE TITLE
The imp module is deprecated in favour of importlib;

### ISSUE THREAD

**Issue by kamyar** [flasgger/flasgger#434]
It seems this line needs to be updated:

https://github.com/flasgger/flasgger/blob/ce98b046cbec2b2eb8c6de6df4b5409c06a8e539/flasgger/utils.py#L5

```
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/imp.py", line 31, in <module>
    warnings.warn("the imp module is deprecated in favour of importlib; "
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```

produced using: `PYTHONWARNINGS=error` in a flask project that uses flasgger.

**Comment by StefanBrand** [comment]
Using `pytest` I get:

```
../usr/local/lib/python3.8/site-packages/flasgger/utils.py:5
  /usr/local/lib/python3.8/site-packages/flasgger/utils.py:5: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

**Comment by saippuakauppias** [comment]
@billyrrr need change only 1 line for fix this

**Comment by mehdies7** [comment]
I still get this warning on V0.9.5

**Comment by fredsonchaves07** [comment]
@mehdies7 
I managed to solve this problem by removing line 5 from the `utils.py` file from the flassger
`import imp`

**Comment by toan-le-theout** [comment]
Hi @billyrrr 

Is the above fix on the latest release? Looks like V0.9.5 still does not have the above fix. Can we have a release with that fix?

**Comment by jfuruness** [comment]
It's not fixed currently

**Comment by jfuruness** [comment]
@billyrrr

**Comment by jfuruness** [comment]
@toan-le-theout For anyone who wants to ignore this error, you can add this line to your requirements.txt file:
git+https://github.com/flasgger/flasgger.git@05e1af4c723c8d975fc37cd88c6af41387dd12e3#egg=flasgger

**Comment by sun-god-gear** [comment]
FYI, this has been fixed as part of the new release of flasgger @ 0.9.7b2
https://github.com/flasgger/flasgger/compare/v0.9.7b1...v0.9.7b2
