### ISSUE TITLE
Parameter in body does not work in pydoc

### ISSUE THREAD

**Issue by danielpcampagna** [flasgger/flasgger#461]
## Description
I've implemented a post route that receives a JSON as a body parameter.
By using the following swagger specification in the pydoc...

```python3
@citations.route("", methods=["POST"])
@swag_from()
def create():
    """
    Use this endpoint to create a new citation.
    ---
    parameters:
        - in: body
            name: body
            required: true
            schema:
                id: data
                properties:
                username:
                    type: string
    responses:
        200:
            description: A JSON object with new Citations.
            schema:
                $ref: '#/definitions/Citation'
            
    """
```
I've got the error:

![Captura de tela de 2021-02-07 21-46-35](https://user-images.githubusercontent.com/7855757/107164521-2b708900-698e-11eb-8f23-608d0ef7f359.png)

## Temporary solution

This error is not raised when I set that specification in the YAML file (and remove it from pydoc)

## Possible related Issues
#428 
#446

**Comment by tientrien2505** [comment]
tab at 'in: body'

**Comment by pycoach** [comment]
@danielpcampagna , use `requestBody` instead of `parameters`.

`/auth/sign-in:
    post:
      tags:
        - auth
      summary: Login
      description: |
        Login with credentials
      operationId: userSignin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
              example:
                  email: user@mail.com
                  password: secret
        description: email and password must be specified.
        required: true`

Hope this could be helpful :)

**Comment by danielpcampagna** [comment]
@pycoach It's work for me, very thankful!
Sorry for the delay. However, I have two points:

1) Where did you find that information? I don't remember seeing that anywhere.
2) Is there a way to use both `requestBody` and `parameters`? I've tried but it did work.

**Comment by danielpcampagna** [comment]
Sorry for the delay.
@pycoach it works! Thanks!
However, I two appointments:
1) where did you find that information? I don't remember seeing that anywhere. Searching on repository I found it in [history](https://github.com/flasgger/flasgger/blob/4bdaed53aa4ed9b315c5f0b651705be526d0b182/HISTORY#L100) and in a [example](https://github.com/flasgger/flasgger/blob/4bdaed53aa4ed9b315c5f0b651705be526d0b182/examples/callbacks.py#L24), however...
2) Actually, it does work just when I use both `parameters` and `requestBody` this way:

```python
@temporary_references.route("/<work_id>/", methods=["POST"])
def create(work_id):
  """
  Creates a new temporary reference for the work_id
  ---
  parameters:
    - in: path
      name: work_id
      required: true
      description: The identity of the base work from which references will be created.
      schema:
        type: string
        example: "pimentel2015b"
    - in: body
      name: body
      required: true
      description: The temporary reference information you want to delete. If it is not informed, will be deleted all temporary references of this work_id
      example: ["L. Murta, V. Braganholo, F. Chirigati, D. Koop, and J. Freire. noWork-flow: Capturing and Analyzing Provenance of Scripts. In International Provenance and Annotation Workshop (IPAW), pages 71–83, Cologne, Germany, 2014."]
  requestBody:
    content:
      application/json:
        schema:
          type: array
          description: The text used in the pdf file.
          items:
            type: string
  responses:
    200:
      description: Returns True, if it was created; False, otherwise.
  """
```
