### ISSUE TITLE
Hide the Models section of the generated Swagger UI

### ISSUE THREAD

**Issue by ayanezeclac** [flasgger/flasgger#500]
Hi, I am struggling trying to hide the Models section located at the bottom of the generated Swagger UI. 

Is it possible to do that?

I have tried adjusting these 'spec' attributes with no success:

model_filter =  lambda tag: False
definition_filter =  lambda tag: False

All other "spec" settings work like a charm.

Any clue?

pd: I've already googled and reviewed the code and issues section of this repository but I can't find a solution.
thanks in advance

**Comment by vuhuycto** [comment]
@ayanezeclac 
I've solved this by doing the trick from [#583](https://github.com/noirbizarre/flask-restplus/issues/583).

**Comment by ayanezeclac** [comment]
@vuhuycto
Thank you very much. It Works!

specs= [
    {
        "title": "My API",
        "description": "Welcome to My API without Model section. <style>.models {display: none !important}</style>",
        "version": "1.0.0",
        "endpoint": 'apispec_1',
	`}
